### ISSUE TITLE
Investigate how to make 𝜇Sensor UI extendable through configuration

### ISSUE THREAD

**Issue by edson-a-soares** [microsensorproject/microsensor#3]
### Description

 * **Problem**: Currently, due to its purely static and monolithic UI, **𝜇Sensor** does not allow any further UI extension without access to its foundational project, which can be a considerable limitation.
 * **Context of Use**: When configuring **𝜇Sensor** on a microservices application the user should be able to extend the tool without needing to rebuild it.
 * **Solution**: Usage of a **configuration manifest** section so that microfrontends could be responsible for rendering specific portions of the UI.

```YAML
- name: Perform a smells analysis.
  id: action_identity
  uses: edson-a-soares/microsensor@development
  with:
    microsensor_manifest:
      project_name:
      project_version:
      asset_imports:
          @your-mfe-name/root-config: https://your-address.com/root-config.js
          @your-mfe-name/summary: https://your-address.com/summary.js
          @your-mfe-name/navbar: https://your-address.com/navbar.js
          @your-mfe-name/shared-libraries: https://your-address.com/shared-libraries.js
          @your-mfe-name/unversioned-apis: https://your-address.com/unversioned-apis.js
          @your-mfe-name/hardcoded-endpoints: https://your-address.com/hardcoded-endpoints.js
        assets_mapping:
        - name: "summary"
 	    assetReference: @your-mfe-name/summary
        - name: shared-libraries
          path: "/shared-libraries"
          assetReference: @your-mfe-name/shared-libraries
        - name: "hardcoded-endpoints"
          path": "/hardcoded-endpoints"
          assetReference: @your-mfe-name/hardcoded-endpoints
```

### Summary

**As a** [developer | researcher]
**I want to** [have configuration control over **𝜇Sensor** UI]
**So that** [I can replace portions of the UI as well as introduce new ones through configuration according to my needs]

### Acceptance Criteria

- [ ] If I set a personalized asset as responsible for a UI portion, then my asset should the in control of rendering that portion of the UI.

### Resources:

* N/A

### Notes

* N/A
